Fixing build

diff --git a/contrib/build-osx/make_osx b/contrib/build-osx/make_osx
--- a/contrib/build-osx/make_osx
+++ b/contrib/build-osx/make_osx
@@ -12,7 +12,7 @@ src_dir=$(dirname "$0")
 cd $src_dir/../..
 
 export PYTHONHASHSEED=22
-VERSION=`git describe --tags --dirty`
+VERSION=1.0
 
 info "Installing Python $PYTHON_VERSION"
 export PATH="~/.pyenv/bin:~/.pyenv/shims:~/Library/Python/3.6/bin:$PATH"
@@ -75,8 +75,8 @@ for d in ~/Library/Python/ ~/.pyenv .; do
 done
 
 info "Building binary"
-info "pyinstaller -n$VERSION contrib/build-osx/osx.spec"
-pyinstaller -n$VERSION contrib/build-osx/osx.spec || fail "Could not build binary"
+info "pyinstaller -n $VERSION contrib/build-osx/osx.spec"
+pyinstaller -n $VERSION contrib/build-osx/osx.spec || fail "Could not build binary"
 
 info "Creating .DMG"
 hdiutil create -fs HFS+ -volname $PACKAGE -srcfolder dist/$PACKAGE.app dist/electrumg-$VERSION.dmg || fail "Could not create .DMG"
